import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(18, GPIO.OUT)
p = GPIO.PWM(18, 50)
p.start(5)
time.sleep(5)

p.ChangeDutyCycle(1)
print("1")
time.sleep(5)
p.ChangeDutyCycle(10)
print("10")
time.sleep(2)
p.ChangeDutyCycle(13)
print("13")
time.sleep(5)
p.ChangeDutyCycle(15)
print("15")
time.sleep(5)
p.ChangeDutyCycle(17)
print("17")
time.sleep(5)
p.ChangeDutyCycle(75)
print("75")
time.sleep(5)
p.ChangeDutyCycle(100)
print("100")
time.sleep(5)

GPIO.cleanup()
